// CodeX with Thapa X Globe — National Anthems Database
// Source: Wikimedia Commons (Public Domain)
const ANTHEMS = {
AF:{name:“Milli Surood”,url:“https://upload.wikimedia.org/wikipedia/commons/3/33/National_anthem_of_Afghanistan.ogg”},
AL:{name:“Hymni i Flamurit”,url:“https://upload.wikimedia.org/wikipedia/commons/2/25/Himni_i_Flamurit.ogg”},
DZ:{name:“Kassaman”,url:“https://upload.wikimedia.org/wikipedia/commons/2/2d/Algeria_anthem.ogg”},
AD:{name:“El Gran Carlemany”,url:“https://upload.wikimedia.org/wikipedia/commons/8/83/El_Gran_Carlemany.ogg”},
AO:{name:“Angola Avante”,url:“https://upload.wikimedia.org/wikipedia/commons/a/ab/Angola_anthem.ogg”},
AG:{name:“Fair Antigua and Barbuda”,url:“https://upload.wikimedia.org/wikipedia/commons/9/96/Antigua_and_Barbuda_anthem.ogg”},
AR:{name:“Himno Nacional Argentino”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9a/Argentina_anthem.ogg”},
AM:{name:“Mer Hayrenik”,url:“https://upload.wikimedia.org/wikipedia/commons/f/f6/Armenia_anthem.ogg”},
AU:{name:“Advance Australia Fair”,url:“https://upload.wikimedia.org/wikipedia/commons/5/51/Australia_anthem.ogg”},
AT:{name:“Bundeshymne”,url:“https://upload.wikimedia.org/wikipedia/commons/3/31/Austria_anthem.ogg”},
AZ:{name:“Azərbaycan marşı”,url:“https://upload.wikimedia.org/wikipedia/commons/3/3f/Azerbaijan_anthem.ogg”},
BS:{name:“March On, Bahamaland”,url:“https://upload.wikimedia.org/wikipedia/commons/5/56/Bahamas_anthem.ogg”},
BH:{name:“Bahrainona”,url:“https://upload.wikimedia.org/wikipedia/commons/2/28/Bahrain_anthem.ogg”},
BD:{name:“Amar Shonar Bangla”,url:“https://upload.wikimedia.org/wikipedia/commons/5/54/Bangladesh_National_Anthem.ogg”},
BB:{name:“In Plenty and In Time of Need”,url:“https://upload.wikimedia.org/wikipedia/commons/8/82/Barbados_anthem.ogg”},
BY:{name:“My Belarusy”,url:“https://upload.wikimedia.org/wikipedia/commons/5/50/Belarus_anthem.ogg”},
BE:{name:“La Brabançonne”,url:“https://upload.wikimedia.org/wikipedia/commons/5/50/Belgium_anthem.ogg”},
BZ:{name:“Land of the Free”,url:“https://upload.wikimedia.org/wikipedia/commons/6/6e/Belize_anthem.ogg”},
BJ:{name:“L’Aube Nouvelle”,url:“https://upload.wikimedia.org/wikipedia/commons/3/37/Benin_anthem.ogg”},
BT:{name:“Druk Tsendhen”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d6/Bhutan_anthem.ogg”},
BO:{name:“Canción Patriótica”,url:“https://upload.wikimedia.org/wikipedia/commons/0/09/Bolivia_anthem.ogg”},
BA:{name:“Jedna si jedina”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e5/Bosnia_and_Herzegovina_anthem.ogg”},
BW:{name:“Fatshe leno la rona”,url:“https://upload.wikimedia.org/wikipedia/commons/4/4a/Botswana_anthem.ogg”},
BR:{name:“Hino Nacional Brasileiro”,url:“https://upload.wikimedia.org/wikipedia/commons/7/7a/Brazil_anthem.ogg”},
BN:{name:“Allah Peliharakan Sultan”,url:“https://upload.wikimedia.org/wikipedia/commons/8/8c/Brunei_anthem.ogg”},
BG:{name:“Mila Rodino”,url:“https://upload.wikimedia.org/wikipedia/commons/6/67/Bulgaria_anthem.ogg”},
BF:{name:“Une Seule Nuit”,url:“https://upload.wikimedia.org/wikipedia/commons/b/bf/Burkina_Faso_anthem.ogg”},
BI:{name:“Burundi Bwacu”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b6/Burundi_anthem.ogg”},
KH:{name:“Nokoreach”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e2/Cambodia_anthem.ogg”},
CM:{name:“Chant de Ralliement”,url:“https://upload.wikimedia.org/wikipedia/commons/0/07/Cameroon_anthem.ogg”},
CA:{name:“O Canada”,url:“https://upload.wikimedia.org/wikipedia/commons/4/40/O_Canada.ogg”},
CV:{name:“Cântico da Liberdade”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b4/Cape_Verde_anthem.ogg”},
CF:{name:“La Renaissance”,url:“https://upload.wikimedia.org/wikipedia/commons/1/18/Central_African_Republic_anthem.ogg”},
TD:{name:“La Tchadienne”,url:“https://upload.wikimedia.org/wikipedia/commons/8/87/Chad_anthem.ogg”},
CL:{name:“Himno Nacional de Chile”,url:“https://upload.wikimedia.org/wikipedia/commons/8/8c/Chile_anthem.ogg”},
CN:{name:“March of the Volunteers”,url:“https://upload.wikimedia.org/wikipedia/commons/1/1e/China_anthem.ogg”},
CO:{name:“Himno Nacional de Colombia”,url:“https://upload.wikimedia.org/wikipedia/commons/0/07/Colombia_anthem.ogg”},
KM:{name:“Udzima wa ya Masiwa”,url:“https://upload.wikimedia.org/wikipedia/commons/0/05/Comoros_anthem.ogg”},
CG:{name:“La Congolaise”,url:“https://upload.wikimedia.org/wikipedia/commons/8/80/Republic_of_the_Congo_anthem.ogg”},
CD:{name:“Debout Congolais”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9b/Democratic_Republic_of_the_Congo_anthem.ogg”},
CR:{name:“Himno Nacional de Costa Rica”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a2/Costa_Rica_anthem.ogg”},
HR:{name:“Lijepa naša domovino”,url:“https://upload.wikimedia.org/wikipedia/commons/0/0e/Croatia_anthem.ogg”},
CU:{name:“La Bayamesa”,url:“https://upload.wikimedia.org/wikipedia/commons/0/06/Cuba_anthem.ogg”},
CY:{name:“Hymn to Liberty”,url:“https://upload.wikimedia.org/wikipedia/commons/9/91/Cyprus_anthem.ogg”},
CZ:{name:“Kde domov můj”,url:“https://upload.wikimedia.org/wikipedia/commons/8/84/Czech_Republic_anthem.ogg”},
DK:{name:“Der er et yndigt land”,url:“https://upload.wikimedia.org/wikipedia/commons/2/26/Denmark_anthem.ogg”},
DJ:{name:“Jabuuti”,url:“https://upload.wikimedia.org/wikipedia/commons/0/08/Djibouti_anthem.ogg”},
DO:{name:“Himno Nacional Dominicano”,url:“https://upload.wikimedia.org/wikipedia/commons/3/37/Dominican_Republic_anthem.ogg”},
CD:{name:“Debout Congolais”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9b/Democratic_Republic_of_the_Congo_anthem.ogg”},
EC:{name:“Salve, Oh Patria”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e4/Ecuador_anthem.ogg”},
EG:{name:“Bilady, Bilady, Bilady”,url:“https://upload.wikimedia.org/wikipedia/commons/5/5e/Egypt_anthem.ogg”},
SV:{name:“Himno Nacional de El Salvador”,url:“https://upload.wikimedia.org/wikipedia/commons/7/72/El_Salvador_anthem.ogg”},
GQ:{name:“Caminemos Pisando las Sendas”,url:“https://upload.wikimedia.org/wikipedia/commons/1/1d/Equatorial_Guinea_anthem.ogg”},
ER:{name:“Ertra, Ertra, Ertra”,url:“https://upload.wikimedia.org/wikipedia/commons/5/59/Eritrea_anthem.ogg”},
EE:{name:“Mu isamaa, mu õnn ja rõõm”,url:“https://upload.wikimedia.org/wikipedia/commons/0/04/Estonia_anthem.ogg”},
SZ:{name:“Nkulunkulu Mnikati wetibusiso temaSwati”,url:“https://upload.wikimedia.org/wikipedia/commons/8/82/Swaziland_anthem.ogg”},
ET:{name:“Whedefit Gesgeshi Woud Henate Ethiopia”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d9/Ethiopia_anthem.ogg”},
FJ:{name:“God Bless Fiji”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c9/Fiji_anthem.ogg”},
FI:{name:“Maamme”,url:“https://upload.wikimedia.org/wikipedia/commons/8/83/Finland_anthem.ogg”},
FR:{name:“La Marseillaise”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a0/France_anthem.ogg”},
GA:{name:“La Concorde”,url:“https://upload.wikimedia.org/wikipedia/commons/9/96/Gabon_anthem.ogg”},
GM:{name:“For The Gambia, Our Homeland”,url:“https://upload.wikimedia.org/wikipedia/commons/0/07/Gambia_anthem.ogg”},
GE:{name:“Tavisupleba”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c7/Georgia_anthem.ogg”},
DE:{name:“Deutschlandlied”,url:“https://upload.wikimedia.org/wikipedia/commons/4/40/Deutschlandlied.ogg”},
GH:{name:“God Bless Our Homeland Ghana”,url:“https://upload.wikimedia.org/wikipedia/commons/9/93/Ghana_anthem.ogg”},
GR:{name:“Hymn to Liberty”,url:“https://upload.wikimedia.org/wikipedia/commons/3/30/Greece_anthem.ogg”},
GD:{name:“Hail Grenada”,url:“https://upload.wikimedia.org/wikipedia/commons/6/66/Grenada_anthem.ogg”},
GT:{name:“Himno Nacional de Guatemala”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e8/Guatemala_anthem.ogg”},
GN:{name:“Liberté”,url:“https://upload.wikimedia.org/wikipedia/commons/2/29/Guinea_anthem.ogg”},
GW:{name:“Esta é a Nossa Pátria Bem Amada”,url:“https://upload.wikimedia.org/wikipedia/commons/1/1b/Guinea-Bissau_anthem.ogg”},
GY:{name:“Dear Land of Guyana”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d0/Guyana_anthem.ogg”},
HT:{name:“La Dessalinienne”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d1/Haiti_anthem.ogg”},
HN:{name:“Tu Bandera es un Lampo de Cielo”,url:“https://upload.wikimedia.org/wikipedia/commons/e/ec/Honduras_anthem.ogg”},
HU:{name:“Himnusz”,url:“https://upload.wikimedia.org/wikipedia/commons/3/3e/Hungary_anthem.ogg”},
IS:{name:“Lofsöngur”,url:“https://upload.wikimedia.org/wikipedia/commons/d/df/Iceland_anthem.ogg”},
IN:{name:“Jana Gana Mana”,url:“https://upload.wikimedia.org/wikipedia/commons/5/55/Jana_Gana_Mana.ogg”},
ID:{name:“Indonesia Raya”,url:“https://upload.wikimedia.org/wikipedia/commons/0/05/Indonesia_Raya.ogg”},
IR:{name:“Soroud-e Mellī-ye Jomhouri-ye Eslāmī-ye Īrān”,url:“https://upload.wikimedia.org/wikipedia/commons/1/15/Iran_anthem.ogg”},
IQ:{name:“Mawtini”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e5/Iraq_anthem.ogg”},
IE:{name:“Amhrán na bhFiann”,url:“https://upload.wikimedia.org/wikipedia/commons/2/2c/Ireland_anthem.ogg”},
IL:{name:“Hatikvah”,url:“https://upload.wikimedia.org/wikipedia/commons/6/6c/Hatikvah_instrumental.ogg”},
IT:{name:“Il Canto degli Italiani”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9a/Italy_anthem.ogg”},
JM:{name:“Jamaica, Land We Love”,url:“https://upload.wikimedia.org/wikipedia/commons/2/2d/Jamaica_anthem.ogg”},
JP:{name:“Kimigayo”,url:“https://upload.wikimedia.org/wikipedia/commons/8/85/Kimigayo_instrumental.ogg”},
JO:{name:“As-Salam al-Malaki al-Urduni”,url:“https://upload.wikimedia.org/wikipedia/commons/4/49/Jordan_anthem.ogg”},
KZ:{name:“Menің Qazaqstanym”,url:“https://upload.wikimedia.org/wikipedia/commons/8/87/Kazakhstan_anthem.ogg”},
KE:{name:“Ee Mungu Nguvu Yetu”,url:“https://upload.wikimedia.org/wikipedia/commons/6/63/Kenya_anthem.ogg”},
KI:{name:“Teirake Kaini Kiribati”,url:“https://upload.wikimedia.org/wikipedia/commons/0/01/Kiribati_anthem.ogg”},
KP:{name:“Aegukka (North Korea)”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b4/North_Korea_anthem.ogg”},
KR:{name:“Aegukga”,url:“https://upload.wikimedia.org/wikipedia/commons/8/84/South_Korea_anthem.ogg”},
KW:{name:“Al-Nasheed Al-Watani”,url:“https://upload.wikimedia.org/wikipedia/commons/6/65/Kuwait_anthem.ogg”},
KG:{name:“Kyrgyz Respublikasynyn Mamlekettik Gimni”,url:“https://upload.wikimedia.org/wikipedia/commons/8/8e/Kyrgyzstan_anthem.ogg”},
LA:{name:“Pheng Xat Lao”,url:“https://upload.wikimedia.org/wikipedia/commons/2/27/Laos_anthem.ogg”},
LV:{name:“Dievs, svētī Latviju!”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d8/Latvia_anthem.ogg”},
LB:{name:“Kulluna lil-watan lil-‘ula lil-‘alam”,url:“https://upload.wikimedia.org/wikipedia/commons/2/29/Lebanon_anthem.ogg”},
LS:{name:“Lesōtho fatše la bo-ntata rōna”,url:“https://upload.wikimedia.org/wikipedia/commons/0/0e/Lesotho_anthem.ogg”},
LR:{name:“All Hail, Liberia, Hail!”,url:“https://upload.wikimedia.org/wikipedia/commons/0/08/Liberia_anthem.ogg”},
LY:{name:“Libya Libya Libya”,url:“https://upload.wikimedia.org/wikipedia/commons/4/4e/Libya_anthem.ogg”},
LT:{name:“Tautiška giesmė”,url:“https://upload.wikimedia.org/wikipedia/commons/8/85/Lithuania_anthem.ogg”},
LU:{name:“Ons Heemecht”,url:“https://upload.wikimedia.org/wikipedia/commons/6/60/Luxembourg_anthem.ogg”},
MG:{name:“Ry Tanindraza nay malala ô”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b0/Madagascar_anthem.ogg”},
MW:{name:“Mulungu dalitsa Malawi”,url:“https://upload.wikimedia.org/wikipedia/commons/9/99/Malawi_anthem.ogg”},
MY:{name:“Negaraku”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e8/Malaysia_anthem.ogg”},
MV:{name:“Gaumii salaam”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b6/Maldives_anthem.ogg”},
ML:{name:“Pour L’Afrique et pour toi Mali”,url:“https://upload.wikimedia.org/wikipedia/commons/4/47/Mali_anthem.ogg”},
MT:{name:“L-Innu Malti”,url:“https://upload.wikimedia.org/wikipedia/commons/2/2d/Malta_anthem.ogg”},
MR:{name:“National Anthem of Mauritania”,url:“https://upload.wikimedia.org/wikipedia/commons/0/0e/Mauritania_anthem.ogg”},
MU:{name:“Motherland”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b8/Mauritius_anthem.ogg”},
MX:{name:“Himno Nacional Mexicano”,url:“https://upload.wikimedia.org/wikipedia/commons/6/68/Mexico_anthem.ogg”},
MD:{name:“Limba noastră”,url:“https://upload.wikimedia.org/wikipedia/commons/d/df/Moldova_anthem.ogg”},
MC:{name:“Hymne Monégasque”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e3/Monaco_anthem.ogg”},
MN:{name:“Mongol ulsyn töriin duulal”,url:“https://upload.wikimedia.org/wikipedia/commons/a/ae/Mongolia_anthem.ogg”},
ME:{name:“Oj, svijetla majska zoro”,url:“https://upload.wikimedia.org/wikipedia/commons/3/36/Montenegro_anthem.ogg”},
MA:{name:“Hymne Chérifien”,url:“https://upload.wikimedia.org/wikipedia/commons/5/5c/Morocco_anthem.ogg”},
MZ:{name:“Pátria Amada”,url:“https://upload.wikimedia.org/wikipedia/commons/d/dc/Mozambique_anthem.ogg”},
MM:{name:“Kaba Ma Kyei”,url:“https://upload.wikimedia.org/wikipedia/commons/2/29/Myanmar_anthem.ogg”},
NA:{name:“Namibia, Land of the Brave”,url:“https://upload.wikimedia.org/wikipedia/commons/2/24/Namibia_anthem.ogg”},
NP:{name:“Sayaun Thunga Phool Ka”,url:“https://upload.wikimedia.org/wikipedia/commons/b/bb/Nepal_National_Anthem.ogg”},
NL:{name:“Het Wilhelmus”,url:“https://upload.wikimedia.org/wikipedia/commons/4/4b/Het_Wilhelmus.ogg”},
NZ:{name:“God Defend New Zealand”,url:“https://upload.wikimedia.org/wikipedia/commons/4/49/New_Zealand_anthem.ogg”},
NI:{name:“Salve a ti Nicaragua”,url:“https://upload.wikimedia.org/wikipedia/commons/a/ab/Nicaragua_anthem.ogg”},
NE:{name:“La Nigérienne”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d3/Niger_anthem.ogg”},
NG:{name:“Arise, O Compatriots”,url:“https://upload.wikimedia.org/wikipedia/commons/8/8f/Nigeria_anthem.ogg”},
MK:{name:“Denes nad Makedonija”,url:“https://upload.wikimedia.org/wikipedia/commons/3/30/North_Macedonia_anthem.ogg”},
NO:{name:“Ja, vi elsker dette landet”,url:“https://upload.wikimedia.org/wikipedia/commons/0/06/Norway_anthem.ogg”},
OM:{name:“Nashid as-Salaam as-Sultani”,url:“https://upload.wikimedia.org/wikipedia/commons/8/80/Oman_anthem.ogg”},
PK:{name:“Qaumī Tarāna”,url:“https://upload.wikimedia.org/wikipedia/commons/6/60/Pakistan_anthem.ogg”},
PW:{name:“Belau rekid”,url:“https://upload.wikimedia.org/wikipedia/commons/5/56/Palau_anthem.ogg”},
PA:{name:“Himno Istmeño”,url:“https://upload.wikimedia.org/wikipedia/commons/3/33/Panama_anthem.ogg”},
PG:{name:“O Arise All You Sons”,url:“https://upload.wikimedia.org/wikipedia/commons/4/4f/Papua_New_Guinea_anthem.ogg”},
PY:{name:“Paraguayos República o Muerte”,url:“https://upload.wikimedia.org/wikipedia/commons/1/10/Paraguay_anthem.ogg”},
PE:{name:“Himno Nacional del Perú”,url:“https://upload.wikimedia.org/wikipedia/commons/e/ea/Peru_anthem.ogg”},
PH:{name:“Lupang Hinirang”,url:“https://upload.wikimedia.org/wikipedia/commons/9/99/Philippines_anthem.ogg”},
PL:{name:“Mazurek Dąbrowskiego”,url:“https://upload.wikimedia.org/wikipedia/commons/b/bc/Mazurek_D%C4%85browskiego_instrumental.ogg”},
PT:{name:“A Portuguesa”,url:“https://upload.wikimedia.org/wikipedia/commons/9/94/Portugal_anthem.ogg”},
QA:{name:“As-Salam al-Amiri”,url:“https://upload.wikimedia.org/wikipedia/commons/0/06/Qatar_anthem.ogg”},
RO:{name:“Deșteaptă-te, române!”,url:“https://upload.wikimedia.org/wikipedia/commons/f/f7/Romania_anthem.ogg”},
RU:{name:“State Anthem of the Russian Federation”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a9/Russia_anthem.ogg”},
RW:{name:“Rwanda Nziza”,url:“https://upload.wikimedia.org/wikipedia/commons/5/55/Rwanda_anthem.ogg”},
KN:{name:“O Land of Beauty!”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c1/Saint_Kitts_and_Nevis_anthem.ogg”},
LC:{name:“Sons and Daughters of Saint Lucia”,url:“https://upload.wikimedia.org/wikipedia/commons/0/08/Saint_Lucia_anthem.ogg”},
VC:{name:“St. Vincent Land So Beautiful”,url:“https://upload.wikimedia.org/wikipedia/commons/e/eb/Saint_Vincent_and_the_Grenadines_anthem.ogg”},
WS:{name:“The Banner of Freedom”,url:“https://upload.wikimedia.org/wikipedia/commons/3/33/Samoa_anthem.ogg”},
SA:{name:“An-Nasheed al-Watanee”,url:“https://upload.wikimedia.org/wikipedia/commons/9/91/Saudi_Arabia_anthem.ogg”},
SN:{name:“Pincez Tous vos Koras”,url:“https://upload.wikimedia.org/wikipedia/commons/a/ab/Senegal_anthem.ogg”},
RS:{name:“Bože pravde”,url:“https://upload.wikimedia.org/wikipedia/commons/4/46/Serbia_anthem.ogg”},
SC:{name:“Koste Seselwa”,url:“https://upload.wikimedia.org/wikipedia/commons/3/33/Seychelles_anthem.ogg”},
SL:{name:“High We Exalt Thee, Realm of the Free”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a7/Sierra_Leone_anthem.ogg”},
SG:{name:“Majulah Singapura”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b9/Singapore_anthem.ogg”},
SK:{name:“Nad Tatrou sa blýska”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d3/Slovakia_anthem.ogg”},
SI:{name:“Zdravljica”,url:“https://upload.wikimedia.org/wikipedia/commons/3/33/Slovenia_anthem.ogg”},
SB:{name:“God Save Our Solomon Islands”,url:“https://upload.wikimedia.org/wikipedia/commons/5/59/Solomon_Islands_anthem.ogg”},
SO:{name:“Qolobaa Calankeed”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e9/Somalia_anthem.ogg”},
ZA:{name:“Nkosi Sikelel’ iAfrika”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9a/South_Africa_anthem.ogg”},
SS:{name:“South Sudan Oyee!”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b0/South_Sudan_anthem.ogg”},
ES:{name:“Marcha Real”,url:“https://upload.wikimedia.org/wikipedia/commons/2/23/Spain_anthem.ogg”},
LK:{name:“Sri Lanka Matha”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e5/Sri_Lanka_anthem.ogg”},
SD:{name:“Nahnu Jund Allah Jund Al-Watan”,url:“https://upload.wikimedia.org/wikipedia/commons/9/97/Sudan_anthem.ogg”},
SR:{name:“God Be With Us”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c1/Suriname_anthem.ogg”},
SE:{name:“Du gamla, Du fria”,url:“https://upload.wikimedia.org/wikipedia/commons/0/03/Sweden_anthem.ogg”},
CH:{name:“Swiss Psalm”,url:“https://upload.wikimedia.org/wikipedia/commons/0/05/Switzerland_anthem.ogg”},
SY:{name:“Humat ad-Diyar”,url:“https://upload.wikimedia.org/wikipedia/commons/1/13/Syria_anthem.ogg”},
TJ:{name:“Surudi Millī”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c3/Tajikistan_anthem.ogg”},
TZ:{name:“Mungu ibariki Afrika”,url:“https://upload.wikimedia.org/wikipedia/commons/d/d9/Tanzania_anthem.ogg”},
TH:{name:“Phleng Chat Thai”,url:“https://upload.wikimedia.org/wikipedia/commons/5/59/Thailand_anthem.ogg”},
TL:{name:“Pátria”,url:“https://upload.wikimedia.org/wikipedia/commons/7/75/East_Timor_anthem.ogg”},
TG:{name:“Terre de nos aïeux”,url:“https://upload.wikimedia.org/wikipedia/commons/2/2c/Togo_anthem.ogg”},
TO:{name:“Ko e fasi ʻo e tuʻi ʻo e ʻOtu Tonga”,url:“https://upload.wikimedia.org/wikipedia/commons/7/74/Tonga_anthem.ogg”},
TT:{name:“Forged From the Love of Liberty”,url:“https://upload.wikimedia.org/wikipedia/commons/3/3c/Trinidad_and_Tobago_anthem.ogg”},
TN:{name:“Ḥumāt al-Ḥimā”,url:“https://upload.wikimedia.org/wikipedia/commons/9/93/Tunisia_anthem.ogg”},
TR:{name:“İstiklâl Marşı”,url:“https://upload.wikimedia.org/wikipedia/commons/3/3c/Turkey_anthem.ogg”},
TM:{name:“Garaşsyz, Bitarap Türkmenistanyň Döwlet Gimni”,url:“https://upload.wikimedia.org/wikipedia/commons/c/c9/Turkmenistan_anthem.ogg”},
UG:{name:“Oh Uganda, Land of Beauty”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a3/Uganda_anthem.ogg”},
UA:{name:“Shche ne vmerla Ukrainy”,url:“https://upload.wikimedia.org/wikipedia/commons/6/6e/Ukraine_anthem.ogg”},
AE:{name:“Ishy Bilady”,url:“https://upload.wikimedia.org/wikipedia/commons/1/14/UAE_anthem.ogg”},
GB:{name:“God Save the King”,url:“https://upload.wikimedia.org/wikipedia/commons/5/58/United_Kingdom_anthem.ogg”},
US:{name:“The Star-Spangled Banner”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e3/US_National_Anthem_instrumental.ogg”},
UY:{name:“Himno Nacional de Uruguay”,url:“https://upload.wikimedia.org/wikipedia/commons/e/e7/Uruguay_anthem.ogg”},
UZ:{name:“O’zbekiston Respublikasining Davlat Madhiyasi”,url:“https://upload.wikimedia.org/wikipedia/commons/a/aa/Uzbekistan_anthem.ogg”},
VE:{name:“Gloria al Bravo Pueblo”,url:“https://upload.wikimedia.org/wikipedia/commons/5/5a/Venezuela_anthem.ogg”},
VN:{name:“Tiến Quân Ca”,url:“https://upload.wikimedia.org/wikipedia/commons/0/0d/Vietnam_anthem.ogg”},
YE:{name:“United Republic”,url:“https://upload.wikimedia.org/wikipedia/commons/b/b5/Yemen_anthem.ogg”},
ZM:{name:“Stand and Sing of Zambia, Proud and Free”,url:“https://upload.wikimedia.org/wikipedia/commons/a/a5/Zambia_anthem.ogg”},
ZW:{name:“Blessed Be the Land of Zimbabwe”,url:“https://upload.wikimedia.org/wikipedia/commons/9/9c/Zimbabwe_anthem.ogg”},
};
